import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import ts from 'typescript';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {player,actions,createEnvironment} from '../lib/game.ts';
import {mapInvitations} from '../lib/place-invitations.ts';
const require=createRequire(import.meta.url),module={exports:{}};
const source=readFileSync(new URL('../app/place-invitations.tsx',import.meta.url),'utf8');
const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ESNext,jsx:ts.JsxEmit.ReactJSX}}).outputText;
vm.runInNewContext(js,{module,exports:module.exports,require:id=>id==='./game-painting'?{default:props=>React.createElement('img',props),__esModule:true}:id==='./game-art'?require('../app/game-art.ts'):id.startsWith('@/')?require('../'+id.slice(2)+'.ts'):require(id)});
const {Invitations,PlaceWelcome,ChoiceTerms,ChoiceBenefit}=module.exports;
const p=player('Welcome'),g={code:'DEMO',mode:'hotseat',host:'x',members:{x:[p.id]},players:[p],status:'playing',round:1,turn:0,maxRounds:8,log:[],seen:[],event:0,rulesVersion:2,...createEnvironment()};
let count=0;const no=()=>count++;
const render=(C,props)=>renderToStaticMarkup(React.createElement(C,props));
for(const place of [...new Set(actions.map(a=>a.place))])assert.ok(render(PlaceWelcome,{place,p,g,onChoose:no}).length>80);
assert.match(render(PlaceWelcome,{place:'MAKERSPACE',p,g,onChoose:no}),/Jo.*Say hello/s);
assert.match(render(PlaceWelcome,{place:'MAKERSPACE',p:{...p,stories:{jo:1}},g,onChoose:no}),/See chapter/);
assert.ok(!render(PlaceWelcome,{place:'MAKERSPACE',p:{...p,rulesVersion:undefined},g,onChoose:no}).includes('Say hello'));
for(const a of actions){const html=render(ChoiceTerms,{p,a,g})+render(ChoiceBenefit,{p,a,g});assert.ok(!/NaN|undefined/.test(html));assert.match(html,/Before you choose/);assert.match(html,/time/);}
const invites=mapInvitations(p,g),html=render(Invitations,{invitations:invites,p,g,disabled:true,onVisit:no});assert.equal((html.match(/disabled=""/g)||[]).length,invites.length);assert.match(html,/A few invitations/);assert.match(html,/Explore at your own pace/);
assert.equal(count,0,'rendering never performs travel or an activity');
const screen=readFileSync(new URL('../app/game-screen.tsx',import.meta.url),'utf8');
assert.ok(screen.indexOf('className="game-action-detail"')<screen.indexOf('className="game-activity-grid"'),'selected action appears before full catalogue in mobile document flow');
assert.match(screen,/firstPlaceAction\(latest.current/);assert.match(screen,/!tutorial.visible&&!tutorialBlocked/);assert.match(screen,/onClick=\{\(\)=>chooseAction\(option.id\)\}/);
assert.match(screen,/options.find\(a=>a.id===firstPlaceAction\(p,visiblePlace/,'after a completed story disappears, the welcome fallback remains legal');
console.log('PASS: all place welcomes and 74 choice presentations render; classic/story guards, disabled invites, no render side effects, selected-action-first flow and tutorial coexistence');
