'use client';
import {useEffect,useRef,useState} from 'react';
import {MapPin,Plus,Minus,LocateFixed,Menu,X,Flag,Wallet,Clock,Zap,Heart,BookOpen,Users,ArrowRight,RotateCw} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {actions,jobs,Player,reason,score} from '@/lib/game';
import {actionPreview,scoreParts} from '@/lib/game-view';
import {locations,locationFor,marbleColors} from '@/lib/locations';
import type {TownControl} from './game-engine';
const money=(n:number)=>'$'+n.toLocaleString('en-US');
export default function GameScreen({g,active,busy,offline,onVisit,onAction,onEnd,onRules,onHome,onCopy}:{g:any;active:boolean;busy:boolean;offline:boolean;onVisit:(place:string)=>Promise<any>;onAction:(id:string)=>Promise<any>;onEnd:()=>void;onRules:()=>void;onHome:()=>void;onCopy:()=>void}){
 const p:Player=g.players[g.turn];const host=useRef<HTMLDivElement>(null),engine=useRef<TownControl|null>(null),latest=useRef({g,active,busy});latest.current={g,active,busy};
 const [software,setSoftware]=useState(false);
 const [lowQuality,setLowQuality]=useState(false);
 const [ready,setReady]=useState(false),[loadError,setLoadError]=useState(false),[moving,setMoving]=useState(false),[place,setPlace]=useState<string|null>(null),[menu,setMenu]=useState<'places'|'life'|null>(null),[choice,setChoice]=useState(''),[feedback,setFeedback]=useState(''),[district,setDistrict]=useState(locationFor(p.place).district);
 const movingRef=useRef(false);movingRef.current=moving;
 const alive=useRef(true);
 const pending=useRef<string|null>(null),visitLock=useRef(false),actionLock=useRef(false),timers=useRef<ReturnType<typeof setTimeout>[]>([]),onVisitRef=useRef(onVisit);onVisitRef.current=onVisit;
 function openLocation(location:string){setChoice(actions.find(a=>a.place===location)?.id||'');setPlace(location);setMenu(null);}
 const openRef=useRef(openLocation);openRef.current=openLocation;
 async function visit(location:string){const state=latest.current;if(!state.active||state.busy||movingRef.current||visitLock.current)return;setMenu(null);if(state.g.players[state.g.turn].place===location){openRef.current(location);return;}visitLock.current=true;pending.current=location;setFeedback('Rolling to '+locationFor(location).name+'…');const result=await onVisitRef.current(location);visitLock.current=false;if(!alive.current)return;if(!result){pending.current=null;setFeedback('Move wasn’t confirmed. Check your connection.');return;}timers.current.push(setTimeout(()=>{if(pending.current===location){pending.current=null;setMoving(false);setFeedback('Arrived at '+locationFor(location).name);openRef.current(location);}},1400));}
 const visitRef=useRef(visit);visitRef.current=visit;
 useEffect(()=>{alive.current=true;setLowQuality(window.innerWidth<700);let disposed=false;import('./game-engine').then(({createTown})=>{if(disposed||!host.current)return;engine.current=createTown(host.current,x=>void visitRef.current(x),soft=>{if(!disposed){setReady(true);setSoftware(!!soft);}},isMoving=>{if(disposed)return;setMoving(isMoving);if(!isMoving&&pending.current){const target=pending.current;pending.current=null;setFeedback('Arrived at '+locationFor(target).name);openRef.current(target);}},()=>{setLoadError(true);setReady(false);});const s=latest.current;engine.current.sync(s.g.players,s.g.turn,s.active&&!s.busy);}).catch(()=>{if(!disposed)setLoadError(true);});return()=>{disposed=true;alive.current=false;engine.current?.destroy();engine.current=null;timers.current.forEach(clearTimeout);};},[]);
 useEffect(()=>{engine.current?.sync(g.players,g.turn,active&&!busy&&!moving&&!place&&!menu);},[g,active,busy,moving,place,menu]);
 useEffect(()=>{setPlace(null);setMenu(null);pending.current=null;setFeedback('');},[p.id,g.round]);
 useEffect(()=>{setDistrict(locationFor(p.place).district);},[p.place]);
 const lastPlace=useRef<string|null>(null),lastMenu=useRef<'places'|'life'>('life');if(place)lastPlace.current=place;if(menu)lastMenu.current=menu;const menuView=menu||lastMenu.current;const visiblePlace=place||lastPlace.current;
 const selected=visiblePlace?locationFor(visiblePlace):null,options=actions.filter(a=>a.place===visiblePlace),a=options.find(a=>a.id===choice)||options[0],preview=a?actionPreview(p,a.id):null,why=a?reason(p,a.id):'';
 async function act(){if(!a||actionLock.current||!active||busy||why)return;actionLock.current=true;const before={...p};const result=await onAction(a.id);if(!alive.current)return;if(result){const now=result.players.find((v:Player)=>v.id===before.id);const rewards=[now.cash!==before.cash?`${now.cash>before.cash?'+':'−'}${money(Math.abs(now.cash-before.cash))}`:'',now.skill>before.skill?`+${now.skill-before.skill} skill`:'',now.joy!==before.joy?`${now.joy>before.joy?'+':''}${now.joy-before.joy} happiness`:'',now.social>before.social?`+${now.social-before.social} connections`:''].filter(Boolean);setFeedback(rewards.join(' · ')||'A little progress.');setPlace(null);engine.current?.focus();engine.current?.celebrate();}timers.current.push(setTimeout(()=>{actionLock.current=false;},900));}
 return <section className="game-screen" aria-label="Crosswalk game"><div ref={host} className="engine-host" tabIndex={0} role="application" aria-label="3D town. Drag to orbit, two fingers to pan and pinch to zoom. Arrow keys pan. Press L for accessible places." onKeyDown={e=>{const moves:Record<string,number[]>={ArrowLeft:[-75,0],ArrowRight:[75,0],ArrowUp:[0,-75],ArrowDown:[0,75]};if(moves[e.key]){e.preventDefault();engine.current?.pan(...moves[e.key] as [number,number]);}if(e.key==='+'||e.key==='=')engine.current?.zoom(1.15);if(e.key==='-')engine.current?.zoom(.87);if(e.key.toLowerCase()==='l')setMenu('places');}}/>
 {!ready&&<div className="game-loading"><strong>{loadError?'3D is unavailable here':'Opening the neighborhood…'}</strong><span>{loadError?'You can still play every activity through Places below.':'Building the streets. Rolling the marbles.'}</span></div>}
 <div className="game-top-hud"><button className="game-player-badge" onClick={()=>setMenu('life')} aria-label="Open your life and scores"><i style={{background:marbleColors[g.turn]}}>{g.turn+1}</i><span><strong>{p.name}</strong><small>WEEK {g.round}/8 · {active?'YOUR TURN':'WATCHING'}</small></span></button><div className="game-resource-row"><span><Wallet/><b>{money(p.cash)}</b><small>cash</small></span><span><Clock/><b>{p.hours}/6</b><small>time</small></span><span><Zap/><b>{p.energy}%</b><small>energy</small></span><span><Heart/><b>{p.joy}%</b><small>joy</small></span></div><button className="game-round-button" aria-label="Game menu" onClick={()=>setMenu('life')}><Menu/></button></div>
 <div className="game-district-tabs" role="group" aria-label="Explore a district"><button onClick={()=>{setDistrict('main');engine.current?.district('main');}} aria-pressed={district==='main'}>Main Street</button><button onClick={()=>{setDistrict('west');engine.current?.district('west');}} aria-pressed={district==='west'}>Westside</button></div>
 <div className="game-camera-controls"><button aria-label="Zoom in" onClick={()=>engine.current?.zoom(1.2)}><Plus/></button><button aria-label="Zoom out" onClick={()=>engine.current?.zoom(.83)}><Minus/></button><button aria-label="Find my marble" onClick={()=>engine.current?.focus()}><LocateFixed/></button><button aria-label="Rotate camera" onClick={()=>engine.current?.orbit(1)}><RotateCw/></button></div>
 <div className="game-status" role="status">{offline?'Connection lost. Reconnect above.':busy?'Saving your move…':moving?'Rolling through town…':feedback||(!active?`${p.name} is taking their turn`:'Drag to orbit · tap a building or prop')}</div>
 <div className="game-bottom-hud"><button className="game-tools-button" onClick={()=>setMenu('places')}><MapPin/><span>Places<small>15 to explore</small></span></button><button className="game-current-place" disabled={!active||busy||moving} onClick={()=>openLocation(p.place)}><span>{locationFor(p.place).name}</span><small>{moving?'On the way':'Explore 4 activities'} <ArrowRight size={13}/></small></button><button className="game-end-button" disabled={!active||busy||moving} onClick={onEnd}><Flag/><span>End week<small>{p.hours} time left</small></span></button></div>
 <Dialog open={!!place} onOpenChange={v=>{if(!v)setPlace(null);}}><DialogContent className="game-location-dialog">{selected&&a&&preview&&<><div className="game-scene-banner"><img src={'/locations/'+selected.art+'.webp'} alt={selected.alt}/><div><small>YOU ARRIVED</small><DialogTitle>{selected.name}</DialogTitle><DialogDescription>{p.hours} time blocks left · {money(p.cash)} in your pocket</DialogDescription></div></div><div className="game-location-body"><div className="game-activity-grid" role="group" aria-label={selected.name+' activities'}>{options.map(option=>{const view=actionPreview(p,option.id),lock=reason(p,option.id);return <button key={option.id} aria-pressed={a.id===option.id} onClick={()=>setChoice(option.id)}><strong>{option.title}</strong><small>{option.time} time · {view.cash===0?'Free':`${view.cash>0?'+':'−'}${money(Math.abs(view.cash))}`}</small>{lock&&<em>{lock}</em>}</button>;})}</div><div className="game-action-preview"><strong>{preview.headline}</strong><p>{a.desc}</p><div>{preview.energy!==0&&<span><Zap size={13}/>{preview.energy>0?'+':''}{preview.energy}</span>}{preview.joy!==0&&<span><Heart size={13}/>{preview.joy>0?'+':''}{preview.joy}</span>}{preview.skill>0&&<span><BookOpen size={13}/>+{preview.skill}</span>}{preview.social>0&&<span><Users size={13}/>+{preview.social}</span>}<span><Wallet size={13}/>{money(preview.afterCash)} after</span></div></div><button className="game-do-action" disabled={!active||busy||moving||!!why} onClick={act}>{busy?'Saving…':moving?'Rolling over…':a.title} <ArrowRight size={18}/></button>{why&&<p className="game-action-lock">{why}</p>}</div></>}</DialogContent></Dialog>
 <Dialog open={!!menu} onOpenChange={v=>{if(!v)setMenu(null);}}><DialogContent className="game-menu-dialog"><DialogTitle>{menuView==='places'?'Where to next?':'Your little life'}</DialogTitle><DialogDescription>{menuView==='places'?'Travel is free. Choose a destination.':`${jobs[p.job].name} · $${jobs[p.job].rate}/hour · ${p.social} connections`}</DialogDescription>{menuView==='places'?<div className="game-place-list">{['main','west'].map(d=><div key={d}><h3>{d==='main'?'Main Street':'Westside'}</h3>{locations.filter(s=>s.district===d).map(s=><button key={s.place} disabled={!active||busy||moving} onClick={()=>void visit(s.place)}><img src={'/locations/'+s.art+'.webp'} alt=""/><span><strong>{s.name}</strong><small>{s.hint}</small></span><ArrowRight size={16}/></button>)}</div>)}</div>:<><div className="game-score-list">{g.players.map((q:Player,i:number)=><div key={q.id}><i style={{background:marbleColors[i]}}>{i+1}</i><strong>{q.name}</strong><span>{score(q)} points</span></div>)}</div><div className="game-stat-grid">{scoreParts(p).map(x=><div key={x.label}><span>{x.label}</span><strong>{Number(x.points.toFixed(1))}/{x.max}</strong></div>)}<div><span>Skills</span><strong>{p.skill}/6</strong></div><div><span>Weekly bills</span><strong>{money(p.housing?705:505)}</strong></div></div><p className="game-menu-note">Eight weeks. Best-rounded life wins. Solo goal: 70 points.</p><div className="game-menu-actions"><button disabled={software} aria-pressed={lowQuality} onClick={()=>{const low=!lowQuality;setLowQuality(low);engine.current?.quality(low);}}>{software?'Graphics: compatibility 3D':lowQuality?'Graphics: battery saver':'Graphics: detailed'}</button><button onClick={()=>{setMenu(null);onRules();}}>How to play</button>{g.mode==='online'&&<button onClick={onCopy}>Copy room link</button>}<button onClick={onHome}>Save & return to title</button></div><details><summary>The week so far</summary>{g.log.slice(0,8).map((s:string,i:number)=><p key={i}>{s}</p>)}</details></>}</DialogContent></Dialog>
 </section>;
}
