import * as T from 'three';
import {SVGRenderer} from 'three/addons/renderers/SVGRenderer.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {buildTown} from './town-models';
import {marbleColors} from '@/lib/locations';
import type {Player,Game} from '@/lib/game';
import type {Weather} from '@/lib/weather';
export type TownControl={weather:(weather:Weather|null)=>void;sync:(players:Player[],turn:number,active:boolean,project?:Game['project'])=>void;district:(name:string)=>void;zoom:(factor:number)=>void;pan:(dx:number,dy:number)=>void;orbit:(direction:number)=>void;quality:(low:boolean)=>void;celebrate:()=>void;focus:()=>void;destroy:()=>void};
export function createTown(parent:HTMLElement,onPick:(place:string)=>void,onReady:(software?:boolean)=>void,onTravel:(moving:boolean)=>void,onFailure?:()=>void):TownControl{
 const reducedQuery=window.matchMedia('(prefers-reduced-motion: reduce)');let reduced=reducedQuery.matches,disposed=false,active=false,players:Player[]=[],turn=0,lastPlayer='',moving=false,low=parent.clientWidth<700,now=0,lastFrame=0,frame=0,dirty=true;let currentWeather:Weather|null=null,lastWeatherKey='uninitialized',sunHeight=35,sunSide=5,sunRear=18;
 let gpu:T.WebGLRenderer|null=null;try{gpu=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'low-power'});}catch{}const software=!gpu;const renderer=gpu||new SVGRenderer();if(software)(renderer as SVGRenderer).setPrecision(2);renderer.setClearColor(new T.Color(0xa7c9c2),1);renderer.outputColorSpace=T.SRGBColorSpace;if(gpu){gpu.toneMapping=T.ACESFilmicToneMapping;gpu.toneMappingExposure=1.1;gpu.shadowMap.enabled=true;gpu.shadowMap.type=T.PCFSoftShadowMap;}renderer.domElement.setAttribute('aria-hidden','true');parent.appendChild(renderer.domElement);
 const scene=new T.Scene();scene.background=new T.Color(0xa7c9c2);scene.fog=new T.Fog(0xa7c9c2,80,160);const camera=new T.PerspectiveCamera(42,1,.1,240);camera.position.set(25,33,38);
 const controls=new OrbitControls(camera,renderer.domElement as unknown as HTMLElement);controls.target.set(0,0,0);controls.enableDamping=!reduced;controls.dampingFactor=.12;controls.minDistance=13;controls.maxDistance=66;controls.minPolarAngle=.25;controls.maxPolarAngle=1.12;controls.screenSpacePanning=false;controls.rotateSpeed=.6;controls.maxTargetRadius=115;controls.update();
 if(software)scene.add(new T.AmbientLight(0xfff1dc,.55));const hemisphere=new T.HemisphereLight(0xfff3d9,0x608374,software?.8:2.1);scene.add(hemisphere);const sun=new T.DirectionalLight(0xffe4b4,software?.85:3.2);sun.position.set(5,35,18);sun.castShadow=true;sun.shadow.camera.left=-35;sun.shadow.camera.right=35;sun.shadow.camera.top=35;sun.shadow.camera.bottom=-35;sun.shadow.camera.near=.5;sun.shadow.camera.far=100;sun.shadow.bias=-.0007;sun.shadow.normalBias=.05;scene.add(sun);scene.add(sun.target);
 const town=buildTown(scene,software),spot=(place:string)=>town.spots.find(s=>s.place===place)||town.spots[0];
 // Persistent neighborhood changes use the same warm, low-poly materials as the town.
 const progressGeometries:T.BufferGeometry[]=[],progressMaterials:T.Material[]=[];
 function progressMesh(parent:T.Object3D,geometry:T.BufferGeometry,color:number,x:number,y:number,z:number){progressGeometries.push(geometry);const material=new T.MeshStandardMaterial({color,roughness:.94});progressMaterials.push(material);const mesh=new T.Mesh(geometry,material);mesh.position.set(x,y,z);mesh.castShadow=true;mesh.receiveShadow=true;parent.add(mesh);return mesh;}
 const gardenGrowth=new T.Group(),gardenBlooms=new T.Group(),homeDetails=new T.Group();scene.add(gardenGrowth,gardenBlooms,homeDetails);const gardenCenter=spot('GARDEN').door;
 for(let i=0;i<6;i++){const x=gardenCenter.x-3.2+(i%3)*1.1,z=gardenCenter.z+1+Math.floor(i/3)*1.2;progressMesh(gardenGrowth,new T.BoxGeometry(.9,.35,.9),0x94643e,x,.7,z);progressMesh(gardenGrowth,new T.ConeGeometry(.38,.9,6),0x658d47,x,1.23,z);progressMesh(gardenBlooms,new T.IcosahedronGeometry(.23,0),i%2?0xecc65f:0xd88761,x,1.72,z);}
 const homeCenter=spot('APARTMENTS').door;for(const dx of [-2.4,2.4]){progressMesh(homeDetails,new T.BoxGeometry(.9,.5,.9),0xb88259,homeCenter.x+dx,.77,homeCenter.z);progressMesh(homeDetails,new T.IcosahedronGeometry(.62,1),0x839d61,homeCenter.x+dx,1.4,homeCenter.z);}gardenGrowth.visible=gardenBlooms.visible=homeDetails.visible=false;
 const greenhouse=new T.Group();scene.add(greenhouse);for(const dx of [-3.8,-.3])for(const dz of [.3,3])progressMesh(greenhouse,new T.BoxGeometry(.08,2.1,.08),0xa4b4a9,gardenCenter.x+dx,1.42,gardenCenter.z+dz);
 for(const dz of [.3,3])for(const dx of [-2.9,-1.2]){const bar=progressMesh(greenhouse,new T.BoxGeometry(2.15,.08,.08),0xa4b4a9,gardenCenter.x+dx,2.8,gardenCenter.z+dz);bar.rotation.z=dx<-2?.42:-.42;}
 progressMesh(greenhouse,new T.BoxGeometry(.08,.08,2.7),0xa4b4a9,gardenCenter.x-2.05,3.19,gardenCenter.z+1.65);greenhouse.visible=false;
 const weatherCount=96,rainPositions=new Float32Array(weatherCount*6),snowPositions=new Float32Array(weatherCount*3);
 const rainGeometry=new T.BufferGeometry();rainGeometry.setAttribute('position',new T.BufferAttribute(rainPositions,3));const snowGeometry=new T.BufferGeometry();snowGeometry.setAttribute('position',new T.BufferAttribute(snowPositions,3));
 const rainMaterial=new T.LineBasicMaterial({color:0xc4d1d1,transparent:true,opacity:.3,depthWrite:false});const snowMaterial=new T.PointsMaterial({color:0xf5f1e5,size:.12,transparent:true,opacity:.7,depthWrite:false});
 const rain=new T.LineSegments(rainGeometry,rainMaterial),snow=new T.Points(snowGeometry,snowMaterial);rain.frustumCulled=snow.frustumCulled=false;rain.visible=snow.visible=false;scene.add(rain,snow);
 function weather(value:Weather|null){const key=value?.id||'legacy';if(key===lastWeatherKey)return;lastWeatherKey=key;currentWeather=value;town.setWeather(value);dirty=true;
  const season=value?.season||'spring',wet=value?.type==='rain';parent.dataset.season=season;parent.dataset.weather=value?.type||'none';
  const sky=wet?0xa6b7b6:season==='winter'?0xb5c5cd:season==='autumn'?0xc8c0a5:season==='summer'?value?.type==='heat'?0xd6c2a1:0xc3cbb1:0xbdcbbb;
  scene.background=new T.Color(sky);(scene.fog as T.Fog).color.setHex(sky);renderer.setClearColor(new T.Color(sky),1);
  hemisphere.color.setHex(season==='winter'?0xd6e4ee:0xffefd2);hemisphere.groundColor.setHex(season==='winter'?0x74828f:season==='autumn'?0x8f7557:0x6a785d);
  sun.color.setHex(season==='winter'?0xffdfae:wet?0xe6eadf:0xffdfae);sun.intensity=software?(wet?.55:.9):(wet?1.7:2.9);sunHeight=season==='winter'?23:season==='autumn'?28:35;sunSide=season==='winter'?13:5;sunRear=season==='winter'?24:18;
  sun.position.set(controls.target.x+sunSide,sunHeight,controls.target.z+sunRear);greenhouse.visible=season==='winter'&&gardenGrowth.visible;
 }
 function animateWeather(){const enabled=!!gpu&&!low&&!reduced&&(currentWeather?.type==='rain'||currentWeather?.type==='snow');rain.visible=enabled&&currentWeather?.type==='rain';snow.visible=enabled&&currentWeather?.type==='snow';parent.dataset.weatherParticles=enabled?String(weatherCount):'0';if(!enabled)return;
  rain.position.set(controls.target.x,0,controls.target.z);snow.position.copy(rain.position);
  for(let i=0;i<weatherCount;i++){const x=((i*17.731)%42)-21,z=((i*11.913)%34)-17;
   if(rain.visible){const y=18-((now*11+i*.317)%18),j=i*6;rainPositions[j]=x;rainPositions[j+1]=y;rainPositions[j+2]=z;rainPositions[j+3]=x+.12;rainPositions[j+4]=y-.8;rainPositions[j+5]=z+.05;}
   if(snow.visible){const j=i*3;snowPositions[j]=x+Math.sin(now*.5+i)*.5;snowPositions[j+1]=18-((now*1.4+i*.271)%18);snowPositions[j+2]=z+Math.cos(now*.3+i)*.35;}
  }
  if(rain.visible)rainGeometry.attributes.position.needsUpdate=true;if(snow.visible)snowGeometry.attributes.position.needsUpdate=true;
 }
 weather(null);
 function keepsakes(ball:T.Mesh){return ['mina','eli','jo'].map((id,i)=>{const group=new T.Group();ball.add(group);if(id==='jo'){const halo=progressMesh(group,new T.TorusGeometry(.78,.055,6,20),0xc9844e,0,.54,0);halo.rotation.x=Math.PI/2;}else if(id==='eli'){const leaf=progressMesh(group,new T.IcosahedronGeometry(.2,0),0x82b853,-.36,.58,.3);leaf.scale.set(.6,1.5,.6);}else{progressMesh(group,new T.IcosahedronGeometry(.16,0),0xffcf70,.35,.55,.36);}group.visible=false;return group;});}
 const softwareLabels:HTMLButtonElement[]=[];if(software){scene.traverse(o=>{if(o instanceof T.Sprite)o.visible=false;});for(const s of town.spots){const el=document.createElement('button');el.className='world-place-label';el.textContent=s.name;el.onclick=()=>{if(active&&!moving){pulse(s.place);onPick(s.place);}};parent.appendChild(el);softwareLabels.push(el);}}
 parent.dataset.renderer=software?'software-3d':'webgl2';parent.dataset.locations=String(town.spots.length);
 const stripeGeo=new T.TorusGeometry(.643,.018,6,36),stripeMaterial=new T.MeshStandardMaterial({color:0xffe6b9,roughness:.3,metalness:.15});
 const marbleGeo=new T.SphereGeometry(.64,24,16),ringGeo=new T.TorusGeometry(.92,.055,6,32),trailGeo=new T.SphereGeometry(.09,6,4);const ringMaterial=new T.MeshBasicMaterial({color:0xffe0a0});const marbles=new Map<string,{ball:T.Mesh;ring:T.Mesh;place:string;route:T.Vector3[];start:number;duration:number;target:T.Vector3;label:T.Sprite;material:T.MeshPhysicalMaterial;keepsakes:T.Group[]}>();const labels:T.Texture[]=[];
 const particles=Array.from({length:20},(_,i)=>{const m=new T.Mesh(trailGeo,new T.MeshBasicMaterial({color:i%2?0xf8cd7b:0xe6f1b9}));m.visible=false;scene.add(m);return m;});let burst=-100,burstAt=new T.Vector3();
 function pulse(place:string){spot(place).phase=now;}
 function quality(value:boolean){low=value;if(!gpu)return;renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,low?1:1.6));sun.shadow.mapSize.set(low?512:1024,low?512:1024);sun.shadow.map?.dispose();sun.shadow.map=null;gpu.shadowMap.needsUpdate=true;}
 function resize(){dirty=true;const w=parent.clientWidth||1,h=parent.clientHeight||1;camera.aspect=w/h;camera.updateProjectionMatrix();renderer.setSize(w,h);}
 quality(low);resize();const observer=new ResizeObserver(resize);observer.observe(parent);
 function frameAt(target:T.Vector3,reset=false){const difference=target.clone().sub(controls.target);if(reset){camera.position.copy(target).add(new T.Vector3(19,27,31));}else camera.position.add(difference);controls.target.copy(target);controls.update();sun.position.set(target.x+sunSide,sunHeight,target.z+sunRear);sun.target.position.set(target.x,0,target.z);sun.target.updateMatrixWorld();}
 function focus(){const p=players[turn];if(p){const s=spot(p.place);frameAt(s.door.clone().multiplyScalar(1).lerp(new T.Vector3(s.district==='west'?52:0,0,0),.3));}}
 function district(name:string){frameAt(new T.Vector3(name==='west'?52:0,0,0),true);}
 function endTravel(){if(moving){moving=false;onTravel(false);}}
 function label(index:number){const c=document.createElement('canvas');c.width=c.height=64;const x=c.getContext('2d')!;x.fillStyle='#fff3d0';x.beginPath();x.arc(32,32,27,0,7);x.fill();x.fillStyle='#214339';x.font='bold 34px Arial';x.textAlign='center';x.textBaseline='middle';x.fillText(String(index+1),32,33);const t=new T.CanvasTexture(c);labels.push(t);const sp=new T.Sprite(new T.SpriteMaterial({map:t,depthTest:false}));sp.scale.set(.65,.65,.65);sp.renderOrder=10;scene.add(sp);if(software)sp.visible=false;return sp;}
 function targetFor(p:Player,index:number){const s=spot(p.place),neighbours=players.filter(q=>q.place===p.place),slot=neighbours.findIndex(q=>q.id===p.id);const target=s.door.clone();target.y=.96;target.x+=(slot-(neighbours.length-1)/2)*1.35;return target;}
 function routeFor(from:string,to:string,start:T.Vector3,end:T.Vector3){const a=spot(from),b=spot(to);const route=[start.clone(),new T.Vector3(a.district==='west'?52:0,.96,0)];if(a.district!==b.district)route.push(new T.Vector3(26,.96,0),new T.Vector3(b.district==='west'?52:0,.96,0));route.push(end.clone());return route;}
 function sync(next:Player[],nextTurn:number,enabled:boolean,project?:Game['project']){gardenGrowth.visible=Object.values(project?.contributions||{}).some(n=>n>0);gardenBlooms.visible=!!project?.completed;homeDetails.visible=next.some(p=>p.housing>0);parent.dataset.garden=project?.completed?'blooming':gardenGrowth.visible?'growing':'empty';parent.dataset.studios=String(next.filter(p=>p.housing>0).length);greenhouse.visible=currentWeather?.season==='winter'&&gardenGrowth.visible;players=next;turn=nextTurn;active=enabled;dirty=true;if(disposed)return;for(let i=0;i<players.length;i++){const p=players[i];let m=marbles.get(p.id);const target=targetFor(p,i);if(!m){const material=new T.MeshPhysicalMaterial({color:marbleColors[i],roughness:.16,metalness:.18,clearcoat:1,clearcoatRoughness:.05});const ball=new T.Mesh(marbleGeo,material);ball.castShadow=true;const stripe=new T.Mesh(stripeGeo,stripeMaterial);stripe.rotation.x=.75;ball.add(stripe);ball.position.copy(target);scene.add(ball);const ring=new T.Mesh(ringGeo,ringMaterial);ring.rotation.x=-Math.PI/2;scene.add(ring);m={ball,ring,material,keepsakes:keepsakes(ball),label:label(i),place:p.place,route:[],start:0,duration:0,target};marbles.set(p.id,m);}if(m.place!==p.place){m.route=routeFor(m.place,p.place,m.ball.position,target);m.start=now;m.duration=reduced||document.hidden?0:1.05;m.place=p.place;m.target=target;if(i===turn){moving=m.duration>0;onTravel(moving);frameAt(target.clone().lerp(new T.Vector3(spot(p.place).district==='west'?52:0,0,0),.3));}pulse(p.place);if(!m.duration){m.ball.position.copy(target);m.route=[];endTravel();}}else if(!m.route.length){m.target=target;m.ball.position.copy(target);}m.keepsakes.forEach((object,k)=>object.visible=(p.stories?.[['mina','eli','jo'][k]]||0)>=3);m.ring.visible=i===turn;m.material.emissive.set(i===turn?0x30200c:0x000000);}if(lastPlayer!==players[turn]?.id){lastPlayer=players[turn]?.id||'';focus();}}
 function along(route:T.Vector3[],t:number){const lengths=route.slice(1).map((v,i)=>v.distanceTo(route[i]));let distance=lengths.reduce((a,b)=>a+b,0)*t;for(let i=0;i<lengths.length;i++){if(distance<=lengths[i]&&lengths[i]>0)return route[i].clone().lerp(route[i+1],distance/lengths[i]);distance-=lengths[i];}return route.at(-1)!.clone();}
 const pointer=new T.Vector2(),ray=new T.Raycaster();let down={x:0,y:0,id:-1},gesture=false;const pointers=new Set<number>();
 function pointerDown(e:PointerEvent){pointers.add(e.pointerId);if(pointers.size>1)gesture=true;else{down={x:e.clientX,y:e.clientY,id:e.pointerId};gesture=false;}}
 function pointerMove(e:PointerEvent){if(Math.hypot(e.clientX-down.x,e.clientY-down.y)>7)gesture=true;}
 function pointerUp(e:PointerEvent){const multi=pointers.size>1;pointers.delete(e.pointerId);if(multi||gesture||e.pointerId!==down.id||!active||moving||disposed)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);ray.setFromCamera(pointer,camera);const props=town.spots.flatMap(s=>s.prop.children);const found=ray.intersectObjects([...props,...town.spots.map(s=>s.hit)],false)[0];if(found){const place=found.object.userData.place as string;pulse(place);onPick(place);}}
 function cancel(e:PointerEvent){pointers.delete(e.pointerId);gesture=true;}
 const canvas=renderer.domElement;canvas.addEventListener('pointerdown',pointerDown as EventListener);canvas.addEventListener('pointermove',pointerMove as EventListener);canvas.addEventListener('pointerup',pointerUp as EventListener);canvas.addEventListener('pointercancel',cancel as EventListener);
 function contextLost(e:Event){e.preventDefault();endTravel();onFailure?.();}
 canvas.addEventListener('webglcontextlost',contextLost);
 function visibility(){if(document.hidden){for(const m of marbles.values()){m.ball.position.copy(m.target);m.route=[];}endTravel();}lastFrame=0;}
 document.addEventListener('visibilitychange',visibility);const preference=()=>{reduced=reducedQuery.matches;controls.enableDamping=!reduced;};reducedQuery.addEventListener('change',preference);
 controls.addEventListener('change',()=>{dirty=true;});
 function animate(ms:number){if(disposed)return;frame=requestAnimationFrame(animate);if(document.hidden)return;const interval=software?1000/15:low?1000/30:1000/60;if(lastFrame&&ms-lastFrame<interval-1)return;const delta=lastFrame?Math.min(.1,(ms-lastFrame)/1000):.016;lastFrame=ms;now=ms/1000;controls.update(delta);controls.target.x=T.MathUtils.clamp(controls.target.x,-27,79);controls.target.z=T.MathUtils.clamp(controls.target.z,-24,24);town.animate(now,reduced);animateWeather();
  for(const [id,m] of marbles){if(m.route.length){const t=m.duration?Math.min(1,(now-m.start)/m.duration):1;const previous=m.ball.position.clone();m.ball.position.copy(along(m.route,t));const movement=m.ball.position.clone().sub(previous);m.ball.rotation.x+=movement.z/.64;m.ball.rotation.z-=movement.x/.64;if(t===1){m.route=[];if(id===players[turn]?.id){pulse(m.place);endTravel();}}}m.ring.position.set(m.ball.position.x,.53,m.ball.position.z);m.ring.scale.setScalar(reduced?1:1+Math.sin(now*3)*.055);m.label.position.copy(m.ball.position).add(new T.Vector3(0,1.08,0));}
  const age=now-burst;particles.forEach((p,i)=>{p.visible=age>=0&&age<1.3&&!reduced;if(p.visible){const a=i*Math.PI*2/particles.length;p.position.copy(burstAt).add(new T.Vector3(Math.cos(a)*age*3,1+age*4-age*age*3,Math.sin(a)*age*3));p.scale.setScalar(1-age/1.3);}});if(!software||dirty||moving||age<1.4||town.spots.some(s=>now-s.phase<2.2)){const renderStart=performance.now();renderer.render(scene,camera);parent.dataset.renderMs=(performance.now()-renderStart).toFixed(1);dirty=false;softwareLabels.forEach((el,i)=>{const s=town.spots[i],v=s.center.clone();v.y=6.7;v.project(camera);const x=(v.x+1)*parent.clientWidth/2,y=(1-v.y)*parent.clientHeight/2;el.style.display=v.z>1||v.z< -1||x<0||x>parent.clientWidth||y<155||y>parent.clientHeight-110?'none':'block';el.style.transform=`translate(-50%,-50%) translate(${x}px,${y}px)`;el.disabled=!active||moving;});}
 }
 frame=requestAnimationFrame(animate);onReady(software);
 return{weather,sync,district,focus,zoom:f=>{camera.position.sub(controls.target).multiplyScalar(1/f).clampLength(13,66).add(controls.target);controls.update();},pan:(dx,dy)=>{const distance=camera.position.distanceTo(controls.target);const right=new T.Vector3().setFromMatrixColumn(camera.matrix,0);right.y=0;right.normalize();const forward=new T.Vector3().crossVectors(new T.Vector3(0,1,0),right);const offset=right.multiplyScalar(dx*distance/1000).add(forward.multiplyScalar(dy*distance/1000));camera.position.add(offset);controls.target.add(offset);controls.update();},orbit:d=>{const offset=camera.position.clone().sub(controls.target).applyAxisAngle(new T.Vector3(0,1,0),d*.35);camera.position.copy(controls.target).add(offset);controls.update();},quality,celebrate:()=>{const p=players[turn];if(p){pulse(p.place);burstAt.copy(spot(p.place).door);burst=now;}},destroy:()=>{if(disposed)return;disposed=true;cancelAnimationFrame(frame);observer.disconnect();document.removeEventListener('visibilitychange',visibility);reducedQuery.removeEventListener('change',preference);canvas.removeEventListener('pointerdown',pointerDown as EventListener);canvas.removeEventListener('pointermove',pointerMove as EventListener);canvas.removeEventListener('pointerup',pointerUp as EventListener);canvas.removeEventListener('pointercancel',cancel as EventListener);canvas.removeEventListener('webglcontextlost',contextLost);controls.dispose();town.dispose();rainGeometry.dispose();snowGeometry.dispose();rainMaterial.dispose();snowMaterial.dispose();progressGeometries.forEach(v=>v.dispose());progressMaterials.forEach(v=>v.dispose());stripeGeo.dispose();stripeMaterial.dispose();marbleGeo.dispose();ringGeo.dispose();trailGeo.dispose();ringMaterial.dispose();marbles.forEach(m=>{m.material.dispose();(m.label.material as T.Material).dispose();});labels.forEach(t=>t.dispose());particles.forEach(p=>(p.material as T.Material).dispose());scene.traverse(o=>{if(o instanceof T.Sprite)o.material.dispose();});gpu?.dispose();gpu?.forceContextLoss();canvas.remove();softwareLabels.forEach(el=>el.remove());}};
}
