'use client';
import {ArrowRight,CalendarDays,Leaf} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {events,Game} from '@/lib/game';
import {getWeather,nextWeather,campaignWeather} from '@/lib/weather';
import GamePainting from './game-painting';
import WeatherIcon from './weather-icon';
import {newsPainting,seasonPainting} from './game-art';
export default function WeeklyNews({g,open,onClose}:{g:Game;open:boolean;onClose:()=>void}){
 const weather=getWeather(g),next=nextWeather(g),event=events[g.event]||events[0];
 return <Dialog open={open} onOpenChange={v=>{if(!v)onClose();}}><DialogContent className="chronicle-dialog"><div className="chronicle-clip" aria-hidden="true"/><header className="chronicle-masthead"><span><Leaf size={18}/> NEIGHBORHOOD EDITION <Leaf size={18}/></span><DialogTitle>The Crosswalk Chronicle</DialogTitle><DialogDescription>{weather?`${weather.season} · Chapter ${weather.chapter}`:'Classic neighborhood'} · Week {g.round} of 8</DialogDescription></header><div className="chronicle-headline"><small>{weather?.timeSkip||'A little news from around the block'}</small><h2>{g.round===1?'A new beginning on your block':event.title}</h2></div><GamePainting className="chronicle-art" src={newsPainting(g.round)} fallback={g.round===2?'/locations/transit.webp':g.round===3?'/locations/cinema.webp':g.round===7?'/locations/market.webp':'/neighborhood.webp'} alt={`Oil painted illustration for ${g.round===1?'a welcoming neighborhood':event.title.toLowerCase()}`} priority/><div className="chronicle-city-news"><span className="news-stamp">{g.round===1?'WELCOME HOME':'CITY NEWS · APPLIED'}</span><p>{g.round===1?'Eight weeks, familiar faces and a few new possibilities. Your little life starts here.':event.text}</p></div>{weather?<div className="chronicle-weather-columns"><section><small>THIS WEEK</small><div className="forecast-title"><WeatherIcon type={weather.type} size={34}/><h3>{weather.label}</h3></div><p>{weather.effectSummary}</p><span>Weather effects apply when you choose an activity</span></section><section><small>{next?'LOOKING AHEAD':'ONE LAST WEEK'}</small>{next?<><div className="forecast-title"><WeatherIcon type={next.type} size={30}/><h3>{next.label}</h3></div><GamePainting className="forecast-painting" src={seasonPainting(next.season)} alt={'The neighborhood in '+next.season}/><p>Week {next.week} · {next.season}</p><span>{next.timeSkip||next.effectSummary}</span></>:<><h3>A year of little moments</h3><p>Make room for the things that matter before the final score.</p></>}</section></div>:<p className="classic-weather-note">This saved game keeps its original rules and economy.</p>}{weather&&<details className="season-calendar"><summary><CalendarDays size={16}/> Your seasonal calendar</summary><p>Two representative weeks in each season. Time skips never add bills.</p><div>{campaignWeather(g).map(w=><span key={w.week} className={w.week===g.round?'current':''}><WeatherIcon type={w.type} size={19}/><b>{w.week}</b><small>{w.season}</small><span>{w.label}</span></span>)}</div></details>}<button className="game-do-action" onClick={onClose}>Explore the week <ArrowRight size={20}/></button></DialogContent></Dialog>;
}
