import {db} from '@/lib/db';
import {Game,player,move,createEnvironment} from '@/lib/game';
export const dynamic='force-dynamic';
async function digest(t:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
function token(req:Request){return req.headers.get('cookie')?.match(/(?:^|; )cw_guest=([a-f0-9]{64})(?:;|$)/)?.[1];}
function view(g:Game,key:string,version:number){const {members,host,seen,...safe}=g;return{...safe,mine:members[key]||[],isHost:host===key,version};}
function reply(data:unknown,status=200,t?:string,req?:Request){const headers:Record<string,string>={'Cache-Control':'no-store'};if(t)headers['Set-Cookie']=`cw_guest=${t}; HttpOnly; SameSite=Strict; Path=/; Max-Age=2592000${req?.url.startsWith('https:')?'; Secure':''}`;return Response.json(data,{status,headers});}
export async function GET(req:Request){try{const code=new URL(req.url).searchParams.get('code')||'';if(!/^[A-Z0-9]{6}$/.test(code))return reply({error:'Enter a six-character room code'},400);const row=await db().prepare('SELECT state, version FROM rooms WHERE code = ?').bind(code).first<{state:string;version:number}>();if(!row)return reply({error:'Room not found. Check the code.'},404);const key=await digest(token(req)||'');const g=JSON.parse(row.state) as Game;if(!g.members[key])return reply({code,status:g.status,players:g.players.map(p=>({name:p.name})),joinable:g.status==='lobby'&&g.mode==='online'&&g.players.length<4},200);return reply(view(g,key,row.version));}catch(e){console.error(e);return reply({error:'Cannot reach the room. Your last saved turn is safe. Try again.'},503);}}
export async function POST(req:Request){try{const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return reply({error:'Invalid request origin'},403);const raw=await req.text();if(raw.length>4096)return reply({error:'Request too large'},413);const b=JSON.parse(raw);let t=token(req),fresh=false;if(!t){t=Array.from(crypto.getRandomValues(new Uint8Array(32))).map(x=>x.toString(16).padStart(2,'0')).join('');fresh=true;}const key=await digest(t);const name=(v:unknown)=>typeof v==='string'?v.trim().slice(0,20):'';
if(b.op==='create'){if(!['online','hotseat'].includes(b.mode))throw Error('Choose a game mode');const names=b.mode==='hotseat'?b.names:[b.name];if(!Array.isArray(names)||names.length<1||names.length>4||names.some(n=>!name(n)))throw Error('Add a name for every player');const code=Array.from(crypto.getRandomValues(new Uint8Array(6))).map(n=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[n%31]).join('');const players=names.map(n=>player(name(n)));const g:Game={code,mode:b.mode,host:key,members:{[key]:players.map(p=>p.id)},players,status:b.mode==='hotseat'?'playing':'lobby',round:1,turn:0,maxRounds:8,log:['Welcome to Crosswalk. Make room for a good life.'],seen:[],event:0,rulesVersion:2,turnsTaken:0,...createEnvironment()};await db().prepare('INSERT INTO rooms (code, state, version, updated_at) VALUES (?, ?, 0, ?)').bind(code,JSON.stringify(g),Date.now()).run();return reply(view(g,key,0),200,fresh?t:undefined,req);}
if(!/^[A-Z0-9]{6}$/.test(b.code||''))throw Error('Invalid room code');const row=await db().prepare('SELECT state, version FROM rooms WHERE code = ?').bind(b.code).first<{state:string;version:number}>();if(!row)return reply({error:'Room not found'},404);const g=JSON.parse(row.state) as Game;
if(b.op==='join'){if(g.members[key])return reply(view(g,key,row.version),200,fresh?t:undefined,req);if(g.status!=='lobby'||g.mode!=='online'||g.players.length>=4)throw Error('This room is no longer accepting players');if(!name(b.name))throw Error('Enter your name');const p=player(name(b.name));if(g.rulesVersion!==2){delete p.rulesVersion;delete p.craft;delete p.legacy;delete p.stories;delete p.storyWeeks;}g.players.push(p);g.members[key]=[p.id];}
else{if(!g.members[key])return reply({error:'Rejoin from the browser where you entered this game'},403);if(typeof b.requestId!=='string'||b.requestId.length>80)throw Error('Invalid move');if(g.seen.includes(b.requestId))return reply(view(g,key,row.version));if(b.version!==row.version)return reply({error:'The room changed. Refreshing your view.'},409);if(b.op==='start'){if(g.host!==key||g.status!=='lobby'||g.players.length<1)throw Error('The host can start once everyone has joined');g.status='playing';}else if(b.op==='move'){if(!g.members[key].includes(g.players[g.turn].id))return reply({error:'It is another player’s turn'},403);move(g,b.action,b.destination);}else throw Error('Unknown request');g.seen=[...g.seen,b.requestId].slice(-100);}
const result=await db().prepare('UPDATE rooms SET state = ?, version = version + 1, updated_at = ? WHERE code = ? AND version = ?').bind(JSON.stringify(g),Date.now(),b.code,row.version).run();if(!result.meta.changes)return reply({error:'Someone just updated the room. Please retry.'},409);return reply(view(g,key,row.version+1),200,fresh?t:undefined,req);
}catch(e){return reply({error:e instanceof Error?e.message:'Something went wrong. Try again.'},400);}}
